phases:
- phase: GettingStarted
  queue: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build GettingStarted
    inputs:
      projects: '.\samples\getting-started\GettingStarted.sln'
- phase: GitHubLabeler
  queue: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build GitHubLabeler
    inputs:
      projects: '.\samples\end-to-end-apps\github-labeler\GitHubLabeler.sln'