phases:
- phase: FSharpGettingStarted
  queue: Hosted VS2017
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build F# GettingStarted
    inputs:
      projects: '.\samples\fsharp\getting-started\GettingStarted.sln'